s3:
  drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/met
  targets:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/targets
  inflow_drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/inflow
  outflow_drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/outflow
  forecasts:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  restart:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
  site_id: ALEX
  name: Lake Alexandrina
  latitude: -35
  longitude: 138
da_setup:
  da_method: enkf
  par_fit_method: perturb_init
  ensemble_size: 217
  localization_distance: .na
  no_negative_states: yes
  assimilate_first_step: no
  use_obs_constraint: yes
  obs_filename: ALEX-targets-insitu.csv
model_settings:
  ncore: 4
  model_name: glm
  base_GLM_nml: glm3.nml
  modeled_depths:
  - 0.0
  - 0.5
  - 1.0
  - 2.0
  - 3.0
  - 4.0
  - 5.0
  - 6.0
  par_config_file: parameter_calibration_config.csv
  obs_config_file: observations_config.csv
  states_config_file: states_config.csv
  depth_model_sd_config_file: depth_model_sd.csv
  max_model_layers: 75
default_init:
  lake_depth: 6.0
  temp:
  - 10.2
  - 10.2
  - 10.2
  - 10.2
  temp_depths:
  - 1.0
  - 3.0
  - 4.0
  - 6.0
  salinity: 0.25
  snow_thickness: 0.0
  white_ice_thickness: 0.0
  blue_ice_thickness: 0.0
flows:
  include_inflow: yes
  include_outflow: yes
  future_inflow_model: future/model_id=combined_inflow/reference_date={reference_date}/site_id={site_id}
  historical_inflow_model: historical/model_id=historical_interp/site_id={site_id}
  future_outflow_model: future/model_id=persistenceRW/reference_date={reference_date}/site_id={site_id}
  historical_outflow_model: historical/model_id=historical_interp/site_id={site_id}
  local_outflow_directory: drivers/outflow
  local_inflow_directory: drivers/inflow
  use_ler_vars: no
  use_flows_s3: no
met:
  future_met_model: gefs-v12/stage2/reference_datetime={reference_date}/site_id={site_id}
  historical_met_model: gefs-v12/stage3/site_id={site_id}
  local_met_directory: drivers/met
  use_ler_vars: no
  forecast_lag_days: 1
  future_met_use_s3: yes
  historical_met_use_s3: yes
  use_openmeteo: no
uncertainty:
  observation: yes
  process: yes
  weather: yes
  initial_condition: yes
  parameter: yes
  met_downscale: yes
  inflow_process: yes
output_settings:
  diagnostics_names: extc
  evaluate_past: yes
  variables_in_scores:
  - state
  - parameter
  generate_plot: yes
  diagnostics_daily:
    names:
    - Tot Inflow Vol
    - flow
    - temp
    - salt
    save_names:
    - inflow
    - overflow_flow
    - overflow_temp
    - overflow_salt
    file:
    - lake.csv
    - overflow.csv
    - overflow.csv
    - overflow.csv
    depth:
    - .na
    - .na
    - .na
    - .na
    - .na
    - .na
    - .na
    - .na
